// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.OpenSourceLicenses
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("domain_content")]
        public bool DomainContent { get; set; }

        [JsonProperty("domain_data")]
        public bool DomainData { get; set; }

        [JsonProperty("domain_software")]
        public bool DomainSoftware { get; set; }

        [JsonProperty("legacy_ids")]
        public string[] LegacyIds { get; set; }

        [JsonProperty("license")]
        public string License { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("license_url")]
        public Uri LicenseUrl { get; set; }

        [JsonProperty("license_status")]
        public string LicenseStatus { get; set; }
    }
}
